server:
  port: 8080
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/taldaysec
    username: postgres
    password: postgres
  mvc:
    async:
      request-timeout: -1
  codec:
    max-in-memory-size: 5000KB