server:
  port: 8081
spring:
  sql:
    init:
      mode: never
      data-locations: [classpath:data.sql, classpath:stats_periods.sql,classpath:stat.sql,classpath:stat_segment.sql, classpath:stat_period.sql,classpath:stat_measure.sql, classpath:stat_info.sql,classpath:stat_info_passport.sql, classpath:stat_data_period.sql]
  datasource:
    url: jdbc:postgresql://localhost:5432/tatatest
    username: postgres
    password: postgres
  mvc:
    async:
      request-timeout: -1
  codec:
    max-in-memory-size: 5000KB