INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('1', '337', 'Миллиард тенге казахских', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('1', '338', 'Триллион тенге казахских', 1000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('1', '77', 'Миллион тенге казахских', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('1', '3', 'Тысяч тенге казахских', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('13', '14', 'Тысяча долларов США', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('13', '367', 'Миллиард долларов США', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('13', '366', 'Миллион долларов США', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('23', '458', 'Миллион человек', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('23', '1534', 'На 10 000 человек', 10000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('23', '131', 'Тысяча человек', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '39', 'Тысяч минут', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '2871', 'Три минуты (тариф)', 3, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '129', 'Сутки', 1440, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '38', 'Час', 60, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '147', 'Неделя', 10080, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '301', 'Миллисекунда', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '302', 'Секунда', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '153', 'Млн.минут', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '300', 'Микросекунда', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '2873', 'Час (тариф)', 60, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '2872', 'Десять минут (тариф)', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '299', 'Наносекунда', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('35', '303', 'Декада', 14400, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '469', 'Сто единиц международных', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '480', 'Тысяча единиц условных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '470', 'Миллион единиц международных', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '481', 'Миллион единиц условных', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '25', 'Тысяча единиц', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '479', 'Единица условная', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '468', 'Единица международная', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('5', '433', 'Миллион единиц', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '178', 'Километр квадратный', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '396', 'Тысяча метров квадратных общей площади', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '398', 'Тысяча метров квадратных жилой площади', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '177', 'Миллион метров квадратных', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '173', 'Миллиметр квадратный', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '186', 'Миля квадратная', 2589988, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '157', 'Ар', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '52', 'Тысяча метров квадратных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '183', 'Фут квадратный', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '181', 'Миллион метров квадратных условных', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '563', 'Кв.м площади жилых и подсобных помещений', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '2843', 'Восемьдесят квадратных метров жилья', 80, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '561', 'Эквивалентные квадратные метры', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '1295', 'Тонна брутто-регистровая', 2, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '187', 'Метр квадратный жилой площади', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '67', 'Гектар', 10000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '397', 'Миллион метров квадратных общей площади', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '400', 'Метр квадратный учебно-лабораторных зданий', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '185', 'Акр', 4046, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '360', 'Метр квадратный общей площади', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '401', 'Тысяча метров квадратных учебно-лабораторных зданий', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '152', 'Тысяча гектаров', 10000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '359', 'Дециметр квадратный', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '402', 'Миллион метров квадратных в двухмиллиметровом исчислении', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '179', 'Метр квадратный условный', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '175', 'Тысяча дециметров квадратных', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '562', 'Кв.м торговой площади', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '182', 'Дюйм квадратный', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '176', 'Миллион дециметров квадратных', 10000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '174', 'Сантиметр квадратный', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '1294', 'Тонна нетто-регистровая', 2, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '180', 'Тысяча метров квадратных условных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('33', '399', 'Миллион метров квадратных жилой площади', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '546', 'Двадцать четыре штуки', 24, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '545', 'Двадцать штук', 20, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '790', 'Триллион штук', 1000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '806', 'Тысяча штук условных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '540', 'Десяток', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '788', 'Сто штук', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '539', 'Шесть штук', 6, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2867', 'Двадцать пять штук', 25, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2531', 'Дюжина штук', 12, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '791', 'Квинтильон штук (Европа)', 1000000000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2851', 'Пятьсот штук', 500, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2869', 'Пятьдесят штук', 50, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '557', 'Штук станов', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '1416', 'Млн. оттисков', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '544', 'Миллион условных штук', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2532', 'Штука условная', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2868', 'Тридцать штук', 30, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2862', 'Две штуки', 2, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '734', 'Миллион штук', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '735', 'Тысяча штук', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2866', 'Шестнадцать штук', 16, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2863', 'Пять штук', 5, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '789', 'Миллиард штук', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2799', 'Десять штук', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('730', '2809', 'Двенадцать штук', 12, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '372', 'Тысяч центнеров', 100000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2835', 'Два килограмма', 2, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2881', 'Тысяча грамм', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '230', 'Гектограмм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '234', 'Тысяча каратов метрических', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2687', 'Двадцать грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '567', 'Килограмм 90 %-ного сухого вещества', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2879', 'Триста грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '235', 'Миллион каратов метрических', 200, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '407', 'Унция СК, США, унция тройская (31,10348 г)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '570', 'Килограмм гидроксида калия', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '259', 'Скрупул СК, США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2841', 'Двадцать пять килограмм', 25, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '250', 'Драхма СК (1,771745 г)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '568', 'Тонна 90 %-ного сухого вещества', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '1097', 'Условная банка, триста пятьдесят грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2877', 'Шестьдесят грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2882', 'Двести сорок грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2875', 'Десять тысяч грамм', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '569', 'Килограмм оксида калия', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '258', 'Тонна длинная СК, США', 1016, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '260', 'Пеннивейт СК, США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '602', 'Грамм делящихся изотопов', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '252', 'Стоун СК', 6, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '21', 'Тонна (метрическая)', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '242', 'Тысяча тонн переработки', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2707', 'Сто грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '241', 'Миллион тонн условного топлива', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '253', 'Квартер СК', 12, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2836', 'Пять килограмм', 5, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2712', 'Двести пятьдесят грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2840', 'Пятнадцать килограмм', 15, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '248', 'Фунт СК, США (0,45359237 кг)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2878', 'Сто двадцать пять грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '255', 'Центнер США', 45, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '263', 'Фунт тройский США (0,373242 кг)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '251', 'Гран СК, США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '566', 'Килограмм пероксида водорода', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '1266', 'Грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '249', 'Унция СК, США (28,349523 г)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '51', 'Тысяча тонн', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '573', 'Килограмм пятиокиси фосфора', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2726', 'Десять грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '236', 'Килотонна', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2842', 'Три тысячи килограмм', 3000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '262', 'Драхма США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '406', 'Грузоподъемность в метрических тоннах', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '231', 'Миллиграмм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '261', 'Драхма СК (3,887935 г)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '137', 'Центнер (гектокилиграмм)', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2838', 'Десять килограмм', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2686', 'Пятнадцать грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '239', 'Сантиграмм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2800', 'Условная банка, четыреста грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '232', 'Карат метрический', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '237', 'Миллион тонн', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '574', 'Килограмм урана', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2818', 'Двадцать пять грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2706', 'Пятьдесят килограмм', 50, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '621', 'Центнер, в пересчете на 100% питательных веществ', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2709', 'Пятьсот грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2876', 'Пятьдесят грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2880', 'Четыреста грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '584', 'Тонна прокатного оборудования', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '257', 'Тонна короткая СК, США', 907, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '405', 'Тысяча тонн единовременного хранения', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '2708', 'Двести грамм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '572', 'Килограмм гидроксида натрия', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '256', 'Центнер длинный СК', 50, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '254', 'Центал СК', 45, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('11', '571', 'Килограмм азота', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('748', '861', 'Тысяч голов', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('47', '81', 'Тысяча киловатт (мегаватт)', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('47', '115', 'МВт', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('47', '266', 'Миллион киловатт (гигаватт)', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('47', '48', 'Киловатт', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('644', '645', 'Центнер кормовых единиц', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2901', 'Тридцать миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '221', 'Пинта сухая США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '202', 'Тысяча метров кубических плотных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '216', 'Джилл США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '219', 'Галлон жидкостный США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '195', 'Тысяча декалитров', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '73', 'Литр (куб. дм.)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '227', 'Корд', 3, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '564', 'Литр чистого спирта', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2716', 'Двести пятьдесят миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '218', 'Кварта жидкостная США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '193', 'Сантилитр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2848', 'Тысяча миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2830', 'Сорок миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2864', 'Двести  кубических метров (воды)', 200, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '223', 'Галлон сухой США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '217', 'Пинта жидкостная США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '222', 'Кварта сухая США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2903', 'Сто двадцать пять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2833', 'Двести семьдесят пять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '220', 'Баррель (нефтяной) США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '565', 'Гектолитр чистого спирта', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2832', 'Двести миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2847', 'Семьсот пятьдесят миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2896', 'Сто двадцать миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '376', 'Сто пятьдесят миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2850', 'Десять  литров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2844', 'Пять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2839', 'Двадцать пять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2715', 'Сто десять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '72', 'Тысяча метров кубических', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '404', 'Тысяча метров кубических приведенных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2845', 'Четыреста миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '208', 'Метр кубический вместимости', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '189', 'Миллиметр кубический', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '374', 'Пятнадцать миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2831', 'Пятьдесят миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '214', 'Бушель СК', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '403', 'Миллион метров кубических переработки газа', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '224', 'Бушель США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2834', 'Триста миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '197', 'Метр кубический плотный', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '204', 'Миллион полулитров', 500, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2837', 'Триста пятьдесят миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '375', 'Сто миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '209', 'Унция жидкостная СК', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '210', 'Джилл СК', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '215', 'Унция жидкостная США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2894', 'Двадцать миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '190', 'Миллилитр (куб. см.)', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2849', 'Десять тысяч миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '225', 'Баррель сухой США', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '79', 'Миллион метров кубических', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '194', 'Децилитр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '74', 'Тысяча литров', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2860', 'Сорок  кубических метров (воды)', 40, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2861', 'Сто кубических  метров (воды)', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '200', 'Тысяча метров кубических условных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '213', 'Галлон СК', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '373', 'Десять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '199', 'Метр кубический условный', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '196', 'Миллион декалитров', 10000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2846', 'Пятьсот миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2746', 'Один баллон 50 литров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '211', 'Пинта СК', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '203', 'Тысяча полулитров', 5, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '192', 'Декалитр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '212', 'Кварта СК', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '201', 'Мегалитр', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '228', 'Тысяча бордфутов', 2, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '205', 'Дюйм кубический', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '206', 'Фут кубический', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '198', 'Гектолитр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '207', 'Ярд кубический', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '1314', 'Тонна обмерная (фрахтовая)', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '2714', 'Семьдесят пять миллилитров', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('71', '191', 'Миллиард метров кубических', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '145', 'Сантиметр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '164', 'Метр условный', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '165', 'Метр погонный проходки', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '560', 'Тысяча автокилометров', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '159', 'Микрометр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '171', 'Тысяча метров условных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '121', 'Тыс.м', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '167', 'Фут', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '162', 'Миллион метров', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '163', 'Тысяча метров погонных', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '2713', 'Десять метров', 10, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '18', 'Километр (тысяча метров)', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '169', 'Миля уставная (1609,344 м)', 1609, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '160', 'Миллиметр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '635', 'Пог.м', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '168', 'Ярд', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '19', 'Тысяч километров', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '172', 'Километр условных труб', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '158', 'Нанометр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '161', 'Дециметр', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '559', 'Метр условных труб', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '170', 'Миля морская (1852 м)', 1852, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '46', 'Метр погонный', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '188', 'Гектометр', 100, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('17', '166', 'Дюйм', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('549', '552', 'Голов собак', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('549', '2795', 'Миллион голов', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '2747', 'Сто киловатт-час', 100000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '598', 'Тысяча киловатт час (мегаватт-час)', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '2852', 'Пять МВтч', 5000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '597', 'Киловатт-час', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '2853', 'Двадцать МВтч', 20000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '600', 'Миллиард киловатт-часов', 1000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('596', '599', 'Миллион киловатт час (гигаватт-час)', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('104', '279', 'Килокалория в час', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('104', '280', 'Тысяча гигакалорий в час', 1000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('104', '105', 'Гигакалория в час', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('274', '276', 'Гигакалория', 1000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('274', '275', 'Килокалория', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('274', '281', 'Мегакалория', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('274', '278', 'Миллион гигакалорий', 1000000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('274', '277', 'Тысяча гигакалорий', 1000000000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('116', '120', 'Тыс. куб. м/час', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('116', '119', 'Тысяча метров кубических в сутки', 41, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('116', '575', 'Метр кубический в секунду', 3600, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('116', '580', 'Куб. м. газа в час', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('116', '583', 'Тысяча  кубических метров газа в час', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('732', '835', 'Тысяча мест ученических', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('731', '767', 'Тысяча мест', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('742', '840', 'Тысяча коек', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('755', '759', 'Тысяча посещений в смену', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('41', '42', 'Тысяча пассажиро-километров', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('41', '135', 'Миллион пассажиро-километров', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('43', '44', 'Тысяча тонно-километров', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('43', '64', 'Миллион тонно-километров', 1000000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('43', '1634', 'Тысяч тонно-километров брутто', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('57', '58', 'Тысяч поездо-километров', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('59', '61', 'Тысяч локомотиво-километров', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('62', '63', 'Тысяч поездо–часов', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('151', '273', 'Метр в час', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('151', '579', 'Метр в секунду', 0, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('282', '284', 'Килобайт', 8192, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('282', '283', 'Байт', 8, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('282', '285', 'Мегабайт', 8388608, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('282', '2814', 'Гигабайт', 8589934592, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('1278', '1279', 'Мбит/с', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('15', '16', 'Тысяч канало-километров', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('726', '727', 'Тысяч каналов', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('728', '729', 'Тысяча номеров', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '1379', 'Число лет', 12, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '304', 'Квартал', 3, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '306', 'Десятилетие', 120, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '155', 'Год', 12, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '305', 'Полугодие', 6, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '2874', 'Месяц (тариф)', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('154', '2870', 'Двенадцать месяцов (тариф)', 12, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('141', '610', 'Тысяча человеко-дней', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('141', '643', 'Человек в год', 365, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('112', '609', 'Тысяча человеко-часов', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('112', '114', 'Пассажиров в день', 24, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('112', '113', 'Пассажир/час', 1, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('1418', '1419', 'Тысяча тонн условного топлива', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('752', '836', 'Тысяча мест рабочих', 1000, '', true, false) ON CONFLICT DO NOTHING;
INSERT INTO public.stat_measure (stat_measure_id, id, text, kfc, sign, leaf, expand) VALUES ('741', '837', 'Тысяча мест посадочных', 1000, '', true, false) ON CONFLICT DO NOTHING;
